promise 
  .then(data => console.log(data))
  .catch(err => console.log(err));